<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User_email</name>
   <tag></tag>
   <elementGuidId>beda5a72-2c8d-467f-abb0-ef3dbb029140</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='i156d10c1-02ff-11ef-92f1-0102d60e20eb']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i156d10c1-02ff-11ef-92f1-0102d60e20eb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email input&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13759758-6bb5-4e29-a8b8-f04864da5bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e70544c4-2c7f-4643-90a0-60adb3ac8411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i156d10c1-02ff-11ef-92f1-0102d60e20eb</value>
      <webElementGuid>88c375d2-3553-440f-be72-755b47ccc551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>9c5c5b7a-4fc2-4404-9056-360356399443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFieldText</value>
      <webElementGuid>b28f1c9f-0dad-4ff2-96fe-7e28aa196145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email input</value>
      <webElementGuid>c3c460fe-bccc-4f2b-8e51-28aec6f76a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i156d10c1-02ff-11ef-92f1-0102d60e20eb&quot;)</value>
      <webElementGuid>62dddcaa-9a3c-402a-ab64-99d79ff9b1db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='i156d10c1-02ff-11ef-92f1-0102d60e20eb']</value>
      <webElementGuid>1adc6e17-52e3-478a-b59f-47b7c21880bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i156d10c1-02ff-11ef-92f1-0102d60e20eb-row']/div[2]/div/div/input</value>
      <webElementGuid>f5f3c087-87a6-4777-9c9f-0a5360ad0d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>965957fa-1010-43a3-833a-4b1f378d75e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'i156d10c1-02ff-11ef-92f1-0102d60e20eb' and @name = 'email']</value>
      <webElementGuid>67a6a4d8-0129-4d90-885f-1e76bb6de085</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
