<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Project_GaborsNewAutotestProjectEdited</name>
   <tag></tag>
   <elementGuidId>1cc1ed8a-5ad2-4d2c-a3b0-0f43e79705e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='i29e38f73-02ff-11ef-92f1-0102d60e20ebTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i29e38f73-02ff-11ef-92f1-0102d60e20ebTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Gabor's New Autotest Project Edited Gabor's New Autotest Project Edited Test Project Edited. Access : Admin Private&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9b06ffee-563a-48b7-a416-cd508b1e13a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiTitle euiTitle--small euiCard__title</value>
      <webElementGuid>58bedc27-294c-4cad-be95-912fc6c9644b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i29e38f73-02ff-11ef-92f1-0102d60e20ebTitle</value>
      <webElementGuid>d8eb2139-8429-4f78-b883-f0ee097cb500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gabor's New Autotest Project Edited</value>
      <webElementGuid>318c3e6a-8ff0-4f1e-a8d8-3828af43f8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i29e38f73-02ff-11ef-92f1-0102d60e20ebTitle&quot;)</value>
      <webElementGuid>03cf20e0-4995-44f0-9880-5cea80fdd218</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='i29e38f73-02ff-11ef-92f1-0102d60e20ebTitle']</value>
      <webElementGuid>462d29f0-f6d3-405c-a4e0-1ad6ef2b335b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div[4]/div[2]/a/div/div[2]/span</value>
      <webElementGuid>e450c19a-2600-4eb4-899f-4ac9746eafbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public'])[1]/following::span[1]</value>
      <webElementGuid>660e16b2-04ea-40a8-9ab2-548494a4227e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/following::span[4]</value>
      <webElementGuid>62eeed12-98ef-49b4-b4c0-d6953ee967a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[2]/preceding::span[1]</value>
      <webElementGuid>7a320c35-1b7e-4bbd-9bbe-bbdc30a4c207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/div[2]/span</value>
      <webElementGuid>740b257f-2dfb-4e1c-9d4c-8ee191f47954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'i29e38f73-02ff-11ef-92f1-0102d60e20ebTitle' and (text() = concat(&quot;Gabor&quot; , &quot;'&quot; , &quot;s New Autotest Project Edited&quot;) or . = concat(&quot;Gabor&quot; , &quot;'&quot; , &quot;s New Autotest Project Edited&quot;))]</value>
      <webElementGuid>a9b56929-e601-44fa-a262-83cbdc0b27c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
