<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Project_GaborsAutotestProject</name>
   <tag></tag>
   <elementGuidId>50e3f693-2eed-4ca5-995d-874645ad7844</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='i9dadb781-02f7-11ef-abd8-a593ab341ccbTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i9dadb781-02f7-11ef-abd8-a593ab341ccbTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Gabor's Autotest Project Gabor's Autotest Project Test Project. Access : Admin Private&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8a356903-924b-412e-a1e8-e24e81c67da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiTitle euiTitle--small euiCard__title</value>
      <webElementGuid>87e7d8c3-5f07-49cd-8e01-181f17d40fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i9dadb781-02f7-11ef-abd8-a593ab341ccbTitle</value>
      <webElementGuid>d4ed4290-25d0-4bf9-b6fd-56fcb33bafc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gabor's Autotest Project</value>
      <webElementGuid>2e3825dd-0a57-4b98-a13a-eb90ffed859b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i9dadb781-02f7-11ef-abd8-a593ab341ccbTitle&quot;)</value>
      <webElementGuid>2e7a28ae-9ab1-4433-bc52-6a91ddf8c220</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='i9dadb781-02f7-11ef-abd8-a593ab341ccbTitle']</value>
      <webElementGuid>2d2c41eb-4a1c-4a93-85dc-a25b9c9153c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div[4]/div/a/div/div[2]/span</value>
      <webElementGuid>c6528848-4fab-466d-9e5b-e06f312fe24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Project'])[1]/following::span[1]</value>
      <webElementGuid>6c6e2c12-3e71-40d4-8779-4a4a13d419c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::span[13]</value>
      <webElementGuid>875737cc-de33-4c25-9b9b-efe08035fb78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[1]/preceding::span[1]</value>
      <webElementGuid>80c4847a-60f1-4dbc-a4eb-c04a261d8ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>94788f77-d21d-445a-851f-bfd7e8b063ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'i9dadb781-02f7-11ef-abd8-a593ab341ccbTitle' and (text() = concat(&quot;Gabor&quot; , &quot;'&quot; , &quot;s Autotest Project&quot;) or . = concat(&quot;Gabor&quot; , &quot;'&quot; , &quot;s Autotest Project&quot;))]</value>
      <webElementGuid>22a5abbd-7313-45be-8f12-52f125c734a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
