<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Home</name>
   <tag></tag>
   <elementGuidId>20903446-f977-43ae-87c7-213710b18a3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.euiBreadcrumb.euiBreadcrumb--last</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/nav/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Home&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>59802421-bd45-43ec-80a2-4ecfce9a3f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiBreadcrumb euiBreadcrumb--last</value>
      <webElementGuid>12caee30-34a7-4a56-a22e-b3c46251fb33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>923aa9ed-ddcf-4eed-bf05-011bd39ff6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>5cfa0b1b-6286-42b1-ba68-06889cb4cd3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>c2d9c8a9-b621-46f9-9512-5960d90ebd69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;euiPage euiPage--paddingMedium euiPage--grow&quot;]/div[@class=&quot;euiHeader euiHeader--default euiHeader--fixed&quot;]/nav[@class=&quot;euiBreadcrumbs euiHeaderBreadcrumbs euiBreadcrumbs--truncate&quot;]/span[@class=&quot;euiBreadcrumb euiBreadcrumb--last&quot;]</value>
      <webElementGuid>3e7c3670-65ad-4a57-8714-1155c26d21fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/nav/span</value>
      <webElementGuid>03642405-d56a-4a60-9174-4d06d55601a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banshee'])[1]/following::span[1]</value>
      <webElementGuid>3f1ccfa5-3c46-4330-b8f3-b2226932614b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Project'])[1]/preceding::span[11]</value>
      <webElementGuid>87243538-4de6-4478-a158-356c324466cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dev - Stage Test'])[1]/preceding::span[13]</value>
      <webElementGuid>a563eb18-ec63-4af2-abb7-99fc8462baaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Home']/parent::*</value>
      <webElementGuid>4aeebbc3-9742-4aff-86a1-837b948fdb3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/span</value>
      <webElementGuid>04276901-cbfc-4a7b-97a8-1540c9c0018d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Home' and (text() = 'Home' or . = 'Home')]</value>
      <webElementGuid>52fb2765-8111-4d55-9d11-560ac08ee4c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
