<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_HomeUserIcon</name>
   <tag></tag>
   <elementGuidId>df04f65f-2e7a-48bd-9ec0-29fec54d8ed8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='userMenuPopover']/div/button/span/span/span/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.euiAvatar.euiAvatar--s.euiAvatar--user</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;User menu&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f21afa5-dd83-4e5d-83b0-8f19bebb8cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiAvatar euiAvatar--s euiAvatar--user</value>
      <webElementGuid>c13fd18f-042c-4684-9175-47eaac7012f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>gpetras@ea.com</value>
      <webElementGuid>23c968e6-3ea2-4263-9a18-d2212266f55a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>gpetras@ea.com</value>
      <webElementGuid>3915c8b6-de4c-4825-a37c-ae19b8053d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userMenuPopover&quot;)/div[@class=&quot;euiPopover__anchor&quot;]/button[@class=&quot;euiButtonEmpty euiButtonEmpty--text euiHeaderSectionItemButton&quot;]/span[@class=&quot;euiButtonContent euiButtonEmpty__content&quot;]/span[@class=&quot;euiButtonEmpty__text&quot;]/span[@class=&quot;euiHeaderSectionItemButton__content&quot;]/div[@class=&quot;euiAvatar euiAvatar--s euiAvatar--user&quot;]</value>
      <webElementGuid>bc6bb55d-3f58-489f-b0fb-bc3f0f1892e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userMenuPopover']/div/button/span/span/span/div</value>
      <webElementGuid>1593118b-62bf-423f-b52e-74b0294923c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>ac5c5ac6-31c7-45ee-977f-6130cbdd7fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'gpetras@ea.com']</value>
      <webElementGuid>dfb74211-f242-45e6-a0b8-9fe886abb899</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
