<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Box_SlackChannelsForSpikeNotification</name>
   <tag></tag>
   <elementGuidId>90b293be-a9cc-48c5-b609-e879519c9604</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='SpikeNotificationType.NotificationSlackChannel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;SpikeNotificationType.NotificationSlackChannel&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;myChannels&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eeee8da5-7714-4294-900c-152bfc35a492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7eed8a39-9b13-4559-aac5-5a3b9081e597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SpikeNotificationType.NotificationSlackChannel</value>
      <webElementGuid>78c20c32-1809-4d12-b854-cab95df2d3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>myChannels</value>
      <webElementGuid>8f9ec55c-e582-4428-9714-ed4952bf4daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFieldText</value>
      <webElementGuid>deb8c5e2-2870-4afd-a27a-d35852463903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>SlackChannel</value>
      <webElementGuid>066bbdb3-b64b-4183-9191-d614496e8bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idcfd5f43-030f-11ef-9f41-9546ed6e597f-row&quot;)/div[@class=&quot;euiFormRow__fieldWrapper&quot;]/div[@class=&quot;euiFormControlLayout&quot;]/div[@class=&quot;euiFormControlLayout__childrenWrapper&quot;]/input[@class=&quot;euiFieldText&quot;]</value>
      <webElementGuid>afbc3f00-601d-4da2-8955-480417c63d39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='SpikeNotificationType.NotificationSlackChannel']</value>
      <webElementGuid>08e5bc8f-bebc-47c5-bb63-0c005ebf2ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idcfd5f43-030f-11ef-9f41-9546ed6e597f-row']/div[2]/div/div/input</value>
      <webElementGuid>d3570ece-0719-4d0a-a83c-d7c26d2504f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>e0f37a55-9d48-46d2-8586-31e00dc70606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'SpikeNotificationType.NotificationSlackChannel' and @placeholder = 'myChannels']</value>
      <webElementGuid>d0c45e50-b19e-43f3-be2e-56deabfa75db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
