<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Box_AddGoogleAppID</name>
   <tag></tag>
   <elementGuidId>851c5d83-cc42-4403-aca7-8beb04b67e54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='i8ec04841-0339-11ef-a683-493becdcd2d4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i8ec04841-0339-11ef-a683-493becdcd2d4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;AppsIdsString&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bb49defc-056e-45b7-bb18-98355a2d82b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiTextArea euiTextArea--resizeVertical</value>
      <webElementGuid>fcfea488-5630-4cb2-b506-bad8845cb016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>AppsIdsString</value>
      <webElementGuid>34f20cf4-05e5-4ba3-951e-a016e4a01f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>4cd44cb1-1ea9-48cd-90bd-1e272ae069a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>2428893e-58bb-43bc-a247-5456ac8766c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AppsIdsString</value>
      <webElementGuid>6950a25c-3416-4637-9801-6943e1a8742f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i8ec04841-0339-11ef-a683-493becdcd2d4</value>
      <webElementGuid>6b72df62-ac6e-4aa1-96f0-96266c7d0181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i8ec04841-0339-11ef-a683-493becdcd2d4&quot;)</value>
      <webElementGuid>ea011dea-5179-455c-8f44-e4fd5f24ef13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='i8ec04841-0339-11ef-a683-493becdcd2d4']</value>
      <webElementGuid>54aea497-3c11-494a-b014-d58eb6f2b37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i8ec04841-0339-11ef-a683-493becdcd2d4-row']/div/textarea</value>
      <webElementGuid>0f580c22-6db7-4d6d-8b44-fde08046060e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/textarea</value>
      <webElementGuid>5eaa0090-7c2c-425c-bae4-e8537a9c8087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'AppsIdsString' and @id = 'i8ec04841-0339-11ef-a683-493becdcd2d4']</value>
      <webElementGuid>a9f62487-4a88-4a18-9365-a9786c7d546d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
