<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Box_Email AddressForSpikeNotification</name>
   <tag></tag>
   <elementGuidId>08a11a24-2771-4926-a99b-a28405598a26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='SpikeNotificationType.NotificationMails']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;SpikeNotificationType.NotificationMails&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;someone@ea.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3654e349-990c-4127-bfc2-32ea656248bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>780ebd49-57e4-4fff-bbc7-6bb5a608417d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SpikeNotificationType.NotificationMails</value>
      <webElementGuid>bcc46852-c98f-475d-badb-c4467ad7523d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>someone@ea.com</value>
      <webElementGuid>ee7ffad6-d626-4301-a2b8-5ce8897c9f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFieldText euiFieldText--withIcon</value>
      <webElementGuid>a8153cb3-2314-4b1c-94c1-42e3e9dad67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Emails Notifications</value>
      <webElementGuid>141fdd29-cf8e-4932-b175-d241a757b48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idcfd5f41-030f-11ef-9f41-9546ed6e597f-row&quot;)/div[@class=&quot;euiFormRow__fieldWrapper&quot;]/div[@class=&quot;euiFormControlLayout&quot;]/div[@class=&quot;euiFormControlLayout__childrenWrapper&quot;]/input[@class=&quot;euiFieldText euiFieldText--withIcon&quot;]</value>
      <webElementGuid>6328488e-a008-457f-a7d7-a81f9d6b5825</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='SpikeNotificationType.NotificationMails']</value>
      <webElementGuid>3d11c4a1-a4ce-4ab0-b0a3-158b730f354a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idcfd5f41-030f-11ef-9f41-9546ed6e597f-row']/div[2]/div/div/input</value>
      <webElementGuid>43e09574-fefd-40c7-b4d1-bd9430bd5724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>16d7ef62-ec7c-4852-9c78-a498ab567f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'SpikeNotificationType.NotificationMails' and @placeholder = 'someone@ea.com']</value>
      <webElementGuid>d5219824-8e84-4b49-bbd9-53e89ad4decd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
