<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Box_(Feed, , s description.)</name>
   <tag></tag>
   <elementGuidId>415a4fad-e8f4-44ab-ba85-63137174dbc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='idcfc4dd3-030f-11ef-9f41-9546ed6e597f']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idcfc4dd3-030f-11ef-9f41-9546ed6e597f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Feed description&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7f0d08c2-2d33-45b8-81d4-dc80d41dc60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiTextArea euiTextArea--resizeVertical</value>
      <webElementGuid>7d1348f4-ebe5-4d58-8e70-22c8a9a94517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Feed description</value>
      <webElementGuid>1a50f133-522b-4a1e-9f5f-fc7fae6ee474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>140</value>
      <webElementGuid>8d38adb5-82bd-4381-bfd4-b2168bd7d584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>idcfc4dd3-030f-11ef-9f41-9546ed6e597f-help</value>
      <webElementGuid>0c4d4eb9-879c-45bc-b481-f79c290eec44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>19eaac7e-8de3-4806-9287-b64abd65eebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>803ddcb8-5c92-48bb-b06c-b971861bc773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idcfc4dd3-030f-11ef-9f41-9546ed6e597f</value>
      <webElementGuid>b1eb6266-fdf4-4da6-9010-64d32291b8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idcfc4dd3-030f-11ef-9f41-9546ed6e597f&quot;)</value>
      <webElementGuid>28c18d92-9c48-43c6-812f-b7d6889ca21a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='idcfc4dd3-030f-11ef-9f41-9546ed6e597f']</value>
      <webElementGuid>3192bf42-4508-46b3-9b39-554db55105ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idcfc4dd3-030f-11ef-9f41-9546ed6e597f-row']/div/textarea</value>
      <webElementGuid>24e541b3-fcc4-4a3b-b361-b73c73dce44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>06297b58-9ecd-4e8c-a08d-8ae3f855d079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'Description' and @id = 'idcfc4dd3-030f-11ef-9f41-9546ed6e597f']</value>
      <webElementGuid>090f81a3-254b-49b6-bc64-12a4e3ddd484</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
