<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Box_SubReddits</name>
   <tag></tag>
   <elementGuidId>9859719e-e92c-4801-9358-821fb06dfb05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='idcffa931-030f-11ef-9f41-9546ed6e597f']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idcffa931-030f-11ef-9f41-9546ed6e597f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;SubRedditsString&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>48cc8b88-dd74-4392-93ac-50031a87284c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiTextArea euiTextArea--resizeVertical</value>
      <webElementGuid>7e8ae53f-8ee3-4c0d-8d54-9ac70d83ed43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>SubRedditsString</value>
      <webElementGuid>76f3fcf5-f447-4e98-b271-fc600c8875ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>32f80974-0a0b-48cd-8af0-74153957e6b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>7b4b74e7-1073-4358-8ba3-6f7786c51eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubRedditsString</value>
      <webElementGuid>49871160-2482-4a18-819b-54045a2be448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idcffa931-030f-11ef-9f41-9546ed6e597f</value>
      <webElementGuid>6a166237-ee79-4f18-8fb0-79d44f5da001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idcffa931-030f-11ef-9f41-9546ed6e597f&quot;)</value>
      <webElementGuid>3ae80c5d-aa80-48d6-88ec-3e4add63880a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='idcffa931-030f-11ef-9f41-9546ed6e597f']</value>
      <webElementGuid>9090a9e0-9f27-429f-9dae-d335a952fcaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idcffa931-030f-11ef-9f41-9546ed6e597f-row']/div/textarea</value>
      <webElementGuid>b294a29e-3a21-477a-a83c-de371b7e2a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/textarea</value>
      <webElementGuid>1653b171-0fed-4439-96ab-ac8cb3a11218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'SubRedditsString' and @id = 'idcffa931-030f-11ef-9f41-9546ed6e597f']</value>
      <webElementGuid>976592bd-889f-4831-b7b5-796a7e4735f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
