<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Box_Query</name>
   <tag></tag>
   <elementGuidId>25fde6b6-2c70-4933-ae65-70050b96e4cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='idcfc9bf6-030f-11ef-9f41-9546ed6e597f']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idcfc9bf6-030f-11ef-9f41-9546ed6e597f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Query&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c0687101-b9fa-49dd-8fb7-bf30cc9d8149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiTextArea euiTextArea--resizeVertical</value>
      <webElementGuid>5f7f4a5b-f967-49cd-aafd-9edf6053a05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Query</value>
      <webElementGuid>eefd0f69-c6c5-4d4b-b36b-64c6b6abe2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>49b49da8-4602-4ecc-bda2-d2acfc0bb202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>02c0af94-fa4b-43fa-a222-c5ea07f2e489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Query</value>
      <webElementGuid>586707ba-a7ca-46fb-a25a-fafef8e3b63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idcfc9bf6-030f-11ef-9f41-9546ed6e597f</value>
      <webElementGuid>a239ac0a-fcc0-416b-a3d6-619dedf36c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idcfc9bf6-030f-11ef-9f41-9546ed6e597f&quot;)</value>
      <webElementGuid>7fc587c2-8ee8-42ae-9205-c7f6b7df22f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='idcfc9bf6-030f-11ef-9f41-9546ed6e597f']</value>
      <webElementGuid>a69b2112-9a1d-4b32-8f83-c930d2bd9340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idcfc9bf6-030f-11ef-9f41-9546ed6e597f-row']/div/textarea</value>
      <webElementGuid>17f2cec3-f6cf-42e0-883f-18b39d671c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/textarea</value>
      <webElementGuid>3d210b73-7deb-45e1-8183-e8ccdfbd47e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'Query' and @id = 'idcfc9bf6-030f-11ef-9f41-9546ed6e597f']</value>
      <webElementGuid>cc8271ee-f9c4-4f8a-9f41-83b4623c23ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
