<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Box_AddSteamAppID</name>
   <tag></tag>
   <elementGuidId>4e81004d-02d1-4cd0-bacd-95b7239b17be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='i08ce2991-033a-11ef-a683-493becdcd2d4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i08ce2991-033a-11ef-a683-493becdcd2d4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;AppsIdsString&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d5f65be0-2fbe-4f5a-bcc0-8160da388fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiTextArea euiTextArea--resizeVertical</value>
      <webElementGuid>b4f2e471-520f-46df-b0ec-598c267a4233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>AppsIdsString</value>
      <webElementGuid>4d26b7b4-e2c8-4dd1-86e5-b458b162f2bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>d405c4a6-53eb-46d0-a222-1ec4e60fd38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>35dbdc2b-8173-4a2f-9247-a1c9d7bd9fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AppsIdsString</value>
      <webElementGuid>70ce664c-e098-46e9-9822-cc0f2066c461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i08ce2991-033a-11ef-a683-493becdcd2d4</value>
      <webElementGuid>2d9f14ea-af4a-467b-8b9e-08096cb2725f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i08ce2991-033a-11ef-a683-493becdcd2d4&quot;)</value>
      <webElementGuid>8b65cb40-b0bb-4404-9317-632f62ecc3cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='i08ce2991-033a-11ef-a683-493becdcd2d4']</value>
      <webElementGuid>1508cf1b-5b7f-455d-8559-4554e0e38896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i08ce2991-033a-11ef-a683-493becdcd2d4-row']/div/textarea</value>
      <webElementGuid>c166f580-d2d5-4e79-8e5a-db789a9bff08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/textarea</value>
      <webElementGuid>70641e55-78ea-429d-b56d-a5cc9dcf1b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'AppsIdsString' and @id = 'i08ce2991-033a-11ef-a683-493becdcd2d4']</value>
      <webElementGuid>6e979b61-2b7c-4d57-8093-2b63074e8da3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
