<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Box_AdDiscordServerID</name>
   <tag></tag>
   <elementGuidId>21184162-7190-4dcf-b13d-60283dc55ff4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='i41d83691-033a-11ef-a683-493becdcd2d4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i41d83691-033a-11ef-a683-493becdcd2d4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;AppsIdsString&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8dadb130-e42e-4245-a303-92d579df7e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiTextArea euiTextArea--resizeVertical</value>
      <webElementGuid>0788b121-a772-4843-af85-971ced89d2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>AppsIdsString</value>
      <webElementGuid>45f75abb-e338-49d9-9ea4-446ccbfb98cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>27c887c5-ea60-432e-85ab-364353c27241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>f60c8974-add5-41a7-b5c5-d07f5bd39ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AppsIdsString</value>
      <webElementGuid>aa2c0d89-05af-4abd-b14f-dd9c98a9747c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i41d83691-033a-11ef-a683-493becdcd2d4</value>
      <webElementGuid>5f61f7e6-cb3e-4247-8b94-2079bf6db91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i41d83691-033a-11ef-a683-493becdcd2d4&quot;)</value>
      <webElementGuid>faa9b3b0-44ec-4a1b-a983-8f4c91294989</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='i41d83691-033a-11ef-a683-493becdcd2d4']</value>
      <webElementGuid>bf843642-3d48-43a7-abca-57a74d36bc26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i41d83691-033a-11ef-a683-493becdcd2d4-row']/div/textarea</value>
      <webElementGuid>1317d3c5-bef7-44ef-b70b-dec45dbbd6a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/textarea</value>
      <webElementGuid>35200f02-8cda-481b-8654-e0fb8cccc97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'AppsIdsString' and @id = 'i41d83691-033a-11ef-a683-493becdcd2d4']</value>
      <webElementGuid>32f3987f-36f9-466b-9290-f60921f325da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
