<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Box_AddAHQ_Link</name>
   <tag></tag>
   <elementGuidId>d4baaf86-90cc-4b69-a298-aea5443afbbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='i4823da41-039e-11ef-a593-af9600cebe4c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i4823da41-039e-11ef-a593-af9600cebe4c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;SubAhqString&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fa598272-624f-4b2d-bfea-89d46c2dcaf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiTextArea euiTextArea--resizeVertical</value>
      <webElementGuid>a7fa8201-eb0f-4959-8ff6-b6cfc0454ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>SubAhqString</value>
      <webElementGuid>39e15bd8-d1b1-4906-aee3-74a6194259e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>0a794e0e-187e-47cc-8209-a462f21ed444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>ca1d1a57-56e6-4025-ab13-71d9cd959345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubAhqString</value>
      <webElementGuid>dd5b5b3a-5f7d-4b84-a409-5c180b357739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i4823da41-039e-11ef-a593-af9600cebe4c</value>
      <webElementGuid>0ee137e1-7f60-4f57-9564-d35ed0dd071d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i4823da41-039e-11ef-a593-af9600cebe4c&quot;)</value>
      <webElementGuid>6dfc94ad-8b42-4c9a-88aa-e390ddd04ec2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='i4823da41-039e-11ef-a593-af9600cebe4c']</value>
      <webElementGuid>fdb8e86a-5fe8-4dc9-8dfc-33d1f560e61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i4823da41-039e-11ef-a593-af9600cebe4c-row']/div/textarea</value>
      <webElementGuid>541b31bc-484a-4641-a497-588af9cdad51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/textarea</value>
      <webElementGuid>76d6d3e0-05b8-440e-bb7d-84d240dc0e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'SubAhqString' and @id = 'i4823da41-039e-11ef-a593-af9600cebe4c']</value>
      <webElementGuid>dc19117b-da3e-419c-a244-a8a19373ed77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
