<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Box_ValueForThreshold_SpikeNotification</name>
   <tag></tag>
   <elementGuidId>ade6f064-c618-4cf9-93ca-d71afaab6d20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='SpikeNotificationType.NotificationThreshold']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;SpikeNotificationType.NotificationThreshold&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;NotificationThreshold&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8960632d-9cb0-4efc-a920-6ed847f14cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fe555661-b6ae-49c9-929a-298a03e9bf48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SpikeNotificationType.NotificationThreshold</value>
      <webElementGuid>693e98f4-1600-440c-bc1e-b0946fdd9121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFieldText</value>
      <webElementGuid>e2e63418-a4ed-40b5-aa72-b1c0cb1a0b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>NotificationThreshold</value>
      <webElementGuid>ae3104ff-7b40-46ab-9ac7-3ba167770c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3a3d51ed-6a15-4932-985b-7bd2ae4b21d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idcfcea11-030f-11ef-9f41-9546ed6e597f&quot;)/div[@class=&quot;euiFlexItem&quot;]/div[@class=&quot;euiFormControlLayout&quot;]/div[@class=&quot;euiFormControlLayout__childrenWrapper&quot;]/input[@class=&quot;euiFieldText&quot;]</value>
      <webElementGuid>a3716034-14ff-478a-ae69-1716e143f20a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='SpikeNotificationType.NotificationThreshold']</value>
      <webElementGuid>00a7c5c5-9279-44a3-8703-195e0cfdbfed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idcfcea11-030f-11ef-9f41-9546ed6e597f']/div/div/div/input</value>
      <webElementGuid>198ca7c7-0b99-4551-ae3b-e97c6f9315aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>e51b8f7a-dc3c-4f7f-9755-693e74abcaca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'SpikeNotificationType.NotificationThreshold']</value>
      <webElementGuid>2be1e418-9937-44f0-9f51-a007d0a3ac6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
