<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Make the project PublicPrivate</name>
   <tag></tag>
   <elementGuidId>5feac0cb-81ec-4158-988c-370e90c52f71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='id20a1f63-0251-11ef-b564-3faa52f9f025']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id20a1f63-0251-11ef-b564-3faa52f9f025</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'id20a1f63-0251-11ef-b564-3faa52f9f025' and @type = 'button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Private&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2d009112-1a06-4c39-b6db-82783da8343c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id20a1f63-0251-11ef-b564-3faa52f9f025</value>
      <webElementGuid>ab17cd5f-efe2-4237-9a3c-9beb3f8b4560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b99b2e25-320a-4e88-ac61-56d059d80396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiSwitch__button</value>
      <webElementGuid>8bf7b25e-f269-4e99-b17d-70ad6ec4c7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>dfbb0bb3-8635-4946-a9cb-bcbb5fcf288f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fed86fad-ef6e-41c4-8d02-677fd38c54ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>PrivacyLevel</value>
      <webElementGuid>53562cc5-2990-4bdd-9db6-2c8cfde62d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>id20a1f65-0251-11ef-b564-3faa52f9f025</value>
      <webElementGuid>5387237d-93b9-4d09-a7c9-31b036a82a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id20a1f63-0251-11ef-b564-3faa52f9f025&quot;)</value>
      <webElementGuid>0b4483d5-f035-41a9-9563-13a2b97a0460</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='id20a1f63-0251-11ef-b564-3faa52f9f025']</value>
      <webElementGuid>b3b49193-916e-48d1-8772-99269c4a1119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id20a1f61-0251-11ef-b564-3faa52f9f025-row']/div/div/button</value>
      <webElementGuid>0b77705a-5dee-4883-9490-c9b56b8e6dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make the title public or private. Private is the default option.'])[1]/following::button[1]</value>
      <webElementGuid>d2f36b1d-17d3-4f15-9ce0-e9aec3c06711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Level'])[1]/following::button[1]</value>
      <webElementGuid>b29dabe6-a426-41c6-ba45-08d6ad97aa0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private'])[1]/preceding::button[1]</value>
      <webElementGuid>be0c5fce-0444-4a43-ad7c-f192f461183b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jira Project'])[1]/preceding::button[1]</value>
      <webElementGuid>37ffdb5f-5af1-4457-9f37-a7e247e54a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/div/button</value>
      <webElementGuid>2df24763-b3cf-475b-9ad6-4c5a874a8094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'id20a1f63-0251-11ef-b564-3faa52f9f025' and @type = 'button']</value>
      <webElementGuid>a1d09bae-61cd-4371-8870-432b43648cef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
