<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_IncludeAllYoutubeReplies</name>
   <tag></tag>
   <elementGuidId>032f19a6-2c54-49e7-9f97-8d01c6a989d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='i6c916875-033a-11ef-a683-493becdcd2d4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i6c916875-033a-11ef-a683-493becdcd2d4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>29e47de2-b137-4b8e-943a-a0677b271a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i6c916875-033a-11ef-a683-493becdcd2d4</value>
      <webElementGuid>f27d6a27-3295-4fb7-8f9e-b869c27149dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6f789607-caee-49cd-97ae-0cf6cbbb36fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiSwitch__button</value>
      <webElementGuid>9d36ba03-5e1f-4bd0-b6ca-311d63e6e35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>3db52f6e-b5cb-480c-9bd9-76e786e258e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b64d4955-7f83-46de-95f5-da9da1123487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>i6c916877-033a-11ef-a683-493becdcd2d4</value>
      <webElementGuid>b50abcff-3dbc-4bc4-94a1-c3e073bf7246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IncludeAllThreadsComments-controlled</value>
      <webElementGuid>a35f96c0-00f0-4e12-8f1d-ffe8468bb754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i6c916875-033a-11ef-a683-493becdcd2d4&quot;)</value>
      <webElementGuid>71796661-4ee4-433e-a3dc-78dd9ea22e52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='i6c916875-033a-11ef-a683-493becdcd2d4']</value>
      <webElementGuid>80e90690-602e-4d7b-a0df-cfa7f05ea31b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i6c916873-033a-11ef-a683-493becdcd2d4-row']/div/div/button</value>
      <webElementGuid>3cb0d102-ef9c-406c-a77b-adb0bbc2d8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Include All Messages'])[1]/following::button[1]</value>
      <webElementGuid>3b80ed12-867c-4dc8-be11-b4bb4ca28cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Query'])[1]/preceding::button[1]</value>
      <webElementGuid>26fa622a-e0c8-498d-bc09-95783570c2d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supported operands:'])[1]/preceding::button[1]</value>
      <webElementGuid>eb6c5de1-ab06-4038-8e2f-d2005fb1c1d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div/div/div/button</value>
      <webElementGuid>72dbd1e8-fb7d-467b-a98d-14fecd57b0d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'i6c916875-033a-11ef-a683-493becdcd2d4' and @type = 'button' and @name = 'IncludeAllThreadsComments-controlled']</value>
      <webElementGuid>7ec844bc-8c5f-4642-bacc-7377d7d89f98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
