<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Enable Spike Alerts</name>
   <tag></tag>
   <elementGuidId>1aaba5a0-56bc-43fa-9c42-dc8d48c94750</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='idcfcc303-030f-11ef-9f41-9546ed6e597f']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idcfcc303-030f-11ef-9f41-9546ed6e597f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Enable Spike Alerts&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9f51227c-9a3b-4cbb-b1f9-52e460110c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idcfcc303-030f-11ef-9f41-9546ed6e597f</value>
      <webElementGuid>44c9b3af-8657-46ae-9b33-bc59fe80bfb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>12c98db7-d401-4bc2-91de-6bdc2460407e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiSwitch__button</value>
      <webElementGuid>b8ae461b-28d8-4064-a580-13bc78f2659b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>95a6ddff-717c-44e3-bb03-dee4543ad519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a491911e-4b7c-4025-b701-9e01dfbb6028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>idcfcc305-030f-11ef-9f41-9546ed6e597f</value>
      <webElementGuid>8ce8ba41-7a81-4ac1-8b7e-b175f59b5d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SpikeNotificationType.NotificationEnabled</value>
      <webElementGuid>cafac447-d393-4f50-a33f-b051cac823fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idcfcc303-030f-11ef-9f41-9546ed6e597f&quot;)</value>
      <webElementGuid>45c6b92a-bb0b-4c2d-adf2-bc38f5a92e04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='idcfcc303-030f-11ef-9f41-9546ed6e597f']</value>
      <webElementGuid>d0e303f7-82f3-4c3e-b4fc-7fa47af60246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idcfcc301-030f-11ef-9f41-9546ed6e597f-row']/div/div/button</value>
      <webElementGuid>ef99933e-7d26-4bc2-8dd5-58aba4f9728e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable Spike Alerts'])[1]/following::button[1]</value>
      <webElementGuid>5aa0711c-5ca9-49be-b2d7-050bdc00d793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spike Alerts'])[1]/following::button[1]</value>
      <webElementGuid>361659bc-1786-400d-8405-5d73f84d8aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable Spike Alerts'])[2]/preceding::button[1]</value>
      <webElementGuid>c6b80335-c844-40ef-9095-e2d73d36a157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spike Threshold'])[1]/preceding::button[1]</value>
      <webElementGuid>318c604b-8fb4-4d96-8d73-4153f793f0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/div/div/div/button</value>
      <webElementGuid>af03b493-9b2a-4f5e-94d6-5a8d60bb8173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'idcfcc303-030f-11ef-9f41-9546ed6e597f' and @type = 'button' and @name = 'SpikeNotificationType.NotificationEnabled']</value>
      <webElementGuid>14c7f84e-acbe-4ad6-b641-7c1f0aa39688</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
