<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_EnableSentimentAnalysis</name>
   <tag></tag>
   <elementGuidId>6bc4d555-0aa8-4d1f-85fa-35fd373b1862</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='idcfdad63-030f-11ef-9f41-9546ed6e597f']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idcfdad63-030f-11ef-9f41-9546ed6e597f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Enable Sentiment Analysis&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0d16ef02-620c-4e3e-846c-74ea912b911a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idcfdad63-030f-11ef-9f41-9546ed6e597f</value>
      <webElementGuid>9897c552-a8de-452c-8e45-521703ab1477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2b4271be-9d54-4fd0-a30d-9b67bf0c84e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiSwitch__button</value>
      <webElementGuid>a67ea763-5551-4358-9106-a95f7563e268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>ae9200c1-9694-4edd-9d9e-c4a9b6d3a8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9c62b3bf-c532-44c8-8f3e-51b2a65488aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>idcfdad65-030f-11ef-9f41-9546ed6e597f</value>
      <webElementGuid>a6c03cca-19e6-415e-bd93-094960af8e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EnableSentimentAnalysis</value>
      <webElementGuid>d00175f7-003a-45a8-9bf0-a1ad0b80b813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idcfdad63-030f-11ef-9f41-9546ed6e597f&quot;)</value>
      <webElementGuid>d5ac2382-73fe-40d9-8e19-796f007e42d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='idcfdad63-030f-11ef-9f41-9546ed6e597f']</value>
      <webElementGuid>cf711140-833b-46fa-bb69-bbde7b24dd92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idcfdad61-030f-11ef-9f41-9546ed6e597f-row']/div/div/button</value>
      <webElementGuid>33bc642a-6305-4773-ac53-a0f1f945ddfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply a POSITIVE, NEUTRAL, NEGATIVE or MIXED tag to content in your feed'])[1]/following::button[1]</value>
      <webElementGuid>f4b3f4e3-f1d6-428c-9160-1cdca10b0946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable Sentiment Analysis'])[1]/following::button[1]</value>
      <webElementGuid>86f3171c-4dde-4352-badd-9b7556056f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable Sentiment Analysis'])[2]/preceding::button[1]</value>
      <webElementGuid>224cb7c2-a7d1-4e56-a918-79b495eebe20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::button[1]</value>
      <webElementGuid>e8c23c3a-a107-4de0-9533-cd574526c65a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[2]/div/div/div/button</value>
      <webElementGuid>e141c27f-d9a8-43e2-92fb-732df9a5549c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'idcfdad63-030f-11ef-9f41-9546ed6e597f' and @type = 'button' and @name = 'EnableSentimentAnalysis']</value>
      <webElementGuid>8793a873-ba6c-41bc-8336-2616a6d2f50a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
