<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown_Android</name>
   <tag></tag>
   <elementGuidId>00fb7856-e991-4749-9103-62b0300ff963</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Android']/span/span/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Android > span.euiContextMenu__itemLayout.euiContextMenu__itemLayout--top > span.euiContextMenuItem__text > div.euiFlexGroup.euiFlexGroup--gutterLarge.euiFlexGroup--alignItemsCenter.euiFlexGroup--directionRow.euiFlexGroup--responsive > div.euiFlexItem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Android&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>92e9051f-aada-4880-8c33-a0e0004b4ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFlexItem</value>
      <webElementGuid>df031ad6-1e24-4c48-9e7c-46105b44bfbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Android</value>
      <webElementGuid>ab42e692-a509-459d-a01e-a5c62bba9e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Android&quot;)/span[@class=&quot;euiContextMenu__itemLayout euiContextMenu__itemLayout--top&quot;]/span[@class=&quot;euiContextMenuItem__text&quot;]/div[@class=&quot;euiFlexGroup euiFlexGroup--gutterLarge euiFlexGroup--alignItemsCenter euiFlexGroup--directionRow euiFlexGroup--responsive&quot;]/div[@class=&quot;euiFlexItem&quot;]</value>
      <webElementGuid>f0350667-5244-4a15-889b-4f2e1ca137dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='Android']/span/span/div/div</value>
      <webElementGuid>7a13658c-dfc3-402b-a77b-c86431d83c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reddit'])[3]/following::div[2]</value>
      <webElementGuid>a74c0997-092c-494d-be48-c355c05b4134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[1]/following::div[4]</value>
      <webElementGuid>ed0a05f5-6859-4e8a-aacd-585cc9342d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AppStore'])[1]/preceding::div[1]</value>
      <webElementGuid>44d63321-7071-41f4-b2d1-740e14c1b906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ahq'])[1]/preceding::div[3]</value>
      <webElementGuid>a582f7a4-83dd-4a3d-9b0a-336bf68a7c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Android']/parent::*</value>
      <webElementGuid>f8cc78a9-5439-47d0-9d4f-dccc720c0ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/span/span/div/div</value>
      <webElementGuid>ddeb9c74-c66f-49c5-b9e2-f5c46013ed7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Android' or . = 'Android')]</value>
      <webElementGuid>9341f63b-4dfb-4dc8-bb1f-686a61b6efcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
