<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown_YouTube</name>
   <tag></tag>
   <elementGuidId>2df7a569-2abe-4ee1-bc32-97bb0c037405</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='YouTube']/span/span/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#YouTube > span.euiContextMenu__itemLayout.euiContextMenu__itemLayout--top > span.euiContextMenuItem__text > div.euiFlexGroup.euiFlexGroup--gutterLarge.euiFlexGroup--alignItemsCenter.euiFlexGroup--directionRow.euiFlexGroup--responsive > div.euiFlexItem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;YouTube&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>936d6961-37e6-4cc8-bedc-f348447d87b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFlexItem</value>
      <webElementGuid>983d5b71-3f96-4f50-af68-cbb71244182b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YouTube</value>
      <webElementGuid>28b66012-4d56-48fb-b061-77dfde96575e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;YouTube&quot;)/span[@class=&quot;euiContextMenu__itemLayout euiContextMenu__itemLayout--top&quot;]/span[@class=&quot;euiContextMenuItem__text&quot;]/div[@class=&quot;euiFlexGroup euiFlexGroup--gutterLarge euiFlexGroup--alignItemsCenter euiFlexGroup--directionRow euiFlexGroup--responsive&quot;]/div[@class=&quot;euiFlexItem&quot;]</value>
      <webElementGuid>2da69ee5-5f01-4ce1-bde4-f0ec643ff711</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='YouTube']/span/span/div/div</value>
      <webElementGuid>59ca0849-8d1f-4597-91b3-80279cdfca05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discord'])[3]/following::div[2]</value>
      <webElementGuid>ef2245f6-d97e-44df-96c8-ec811b3583fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Steam'])[1]/following::div[4]</value>
      <webElementGuid>7e57bf10-98c9-422a-9f87-e130761929b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='YouTube']/parent::*</value>
      <webElementGuid>c3e4c6d0-2628-424d-8877-0695e85b1047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[8]/span/span/div/div</value>
      <webElementGuid>f03d0908-8f86-41b9-85c4-25566795b38b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'YouTube' or . = 'YouTube')]</value>
      <webElementGuid>6f102856-a779-4c60-848b-c6bb8c2bc48c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
