<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown_Units</name>
   <tag></tag>
   <elementGuidId>b3796d47-4ced-4efa-b855-54ad606a5887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='idcfcea11-030f-11ef-9f41-9546ed6e597f']/div[2]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.euiComboBox__inputWrap.euiComboBox__inputWrap--noWrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Select unit or percentage&quot;i >> div >> internal:has-text=&quot;Units&quot;i >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cbe4cd73-7b77-41d6-8c81-d8d9ba2f23be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiComboBox__inputWrap euiComboBox__inputWrap--noWrap</value>
      <webElementGuid>1344ca11-c436-407a-93fd-bf40184ab3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-subj</name>
      <type>Main</type>
      <value>comboBoxInput</value>
      <webElementGuid>9884bd8b-665e-43a3-9df5-0387ead094ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>436cf050-9651-4c61-9afc-1e23f17b2e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Units</value>
      <webElementGuid>1de7be6d-118c-4517-b0a9-7895dac893a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idcfcea11-030f-11ef-9f41-9546ed6e597f&quot;)/div[@class=&quot;euiFlexItem&quot;]/div[@class=&quot;euiComboBox euiComboBox-isDisabled&quot;]/div[@class=&quot;euiFormControlLayout&quot;]/div[@class=&quot;euiFormControlLayout__childrenWrapper&quot;]/div[@class=&quot;euiComboBox__inputWrap euiComboBox__inputWrap--noWrap&quot;]</value>
      <webElementGuid>7f039f09-e84e-485e-ae4f-97c0d84cb990</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idcfcea11-030f-11ef-9f41-9546ed6e597f']/div[2]/div/div/div/div</value>
      <webElementGuid>112f2fd0-278f-448b-8059-55c6ea53a85e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Define a threshold, in whole numbers, the increase in new data points you would like an alert on.'])[1]/following::div[12]</value>
      <webElementGuid>efd1cf18-c317-4dbf-bde3-75e7dafff234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spike Threshold'])[1]/following::div[14]</value>
      <webElementGuid>59e2c599-0119-4363-9fe8-faa54f71160c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[1]/preceding::div[4]</value>
      <webElementGuid>5691ace5-03cc-4199-bd8a-62aa6b518679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>374fb999-6f13-48cd-bf17-1956817ea539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Units' or . = 'Units')]</value>
      <webElementGuid>2c5dd564-5639-4189-b98b-516b424f0c63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
