<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown_AppStore</name>
   <tag></tag>
   <elementGuidId>88390b28-3f7e-4b6c-9b30-039ba60d92b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='AppStore']/span/span/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AppStore > span.euiContextMenu__itemLayout.euiContextMenu__itemLayout--top > span.euiContextMenuItem__text > div.euiFlexGroup.euiFlexGroup--gutterLarge.euiFlexGroup--alignItemsCenter.euiFlexGroup--directionRow.euiFlexGroup--responsive > div.euiFlexItem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;AppStore&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>700185e7-8438-4ab2-b3f4-fa5cb8380ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFlexItem</value>
      <webElementGuid>b8a33295-67bd-4327-8d6e-b5bdb66bd5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AppStore</value>
      <webElementGuid>e04047d2-53c2-41e3-a9c1-f8ea69ff4bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AppStore&quot;)/span[@class=&quot;euiContextMenu__itemLayout euiContextMenu__itemLayout--top&quot;]/span[@class=&quot;euiContextMenuItem__text&quot;]/div[@class=&quot;euiFlexGroup euiFlexGroup--gutterLarge euiFlexGroup--alignItemsCenter euiFlexGroup--directionRow euiFlexGroup--responsive&quot;]/div[@class=&quot;euiFlexItem&quot;]</value>
      <webElementGuid>9d590f84-0c26-4cf7-b679-2c552ef4cf47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='AppStore']/span/span/div/div</value>
      <webElementGuid>9c4c576b-a08a-4062-b0ee-fe3885019676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Android'])[3]/following::div[2]</value>
      <webElementGuid>3aa7dd78-6d8a-4900-87b1-e539e8e8f31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reddit'])[1]/following::div[4]</value>
      <webElementGuid>98bd08c0-6c66-4456-9b3b-32f2725a1e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ahq'])[1]/preceding::div[1]</value>
      <webElementGuid>5f0178f8-9efe-4621-8aec-4b544e901be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Steam'])[1]/preceding::div[3]</value>
      <webElementGuid>fd5e980b-c74d-416e-9865-000626f01aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AppStore']/parent::*</value>
      <webElementGuid>e9af09df-158e-4bbe-92b6-83fca6be1771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]/span/span/div/div</value>
      <webElementGuid>715d8079-0583-48ec-9a9d-3add4564e989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'AppStore' or . = 'AppStore')]</value>
      <webElementGuid>d29e49d2-5f60-46d6-8197-020544d864e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
