<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown_Discord</name>
   <tag></tag>
   <elementGuidId>782461d6-b005-4443-bba6-85621049e87b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Discord']/span/span/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Discord > span.euiContextMenu__itemLayout.euiContextMenu__itemLayout--top > span.euiContextMenuItem__text > div.euiFlexGroup.euiFlexGroup--gutterLarge.euiFlexGroup--alignItemsCenter.euiFlexGroup--directionRow.euiFlexGroup--responsive > div.euiFlexItem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Discord&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>27509f8b-59a0-4ce9-853a-804314a701d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFlexItem</value>
      <webElementGuid>c5802e9c-529a-4fb8-a8d9-a2667c716a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Discord</value>
      <webElementGuid>b463d4bc-aaf2-49f5-b992-e9c733ec9d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Discord&quot;)/span[@class=&quot;euiContextMenu__itemLayout euiContextMenu__itemLayout--top&quot;]/span[@class=&quot;euiContextMenuItem__text&quot;]/div[@class=&quot;euiFlexGroup euiFlexGroup--gutterLarge euiFlexGroup--alignItemsCenter euiFlexGroup--directionRow euiFlexGroup--responsive&quot;]/div[@class=&quot;euiFlexItem&quot;]</value>
      <webElementGuid>5d733c3a-939c-430b-a7f4-a3471a262292</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='Discord']/span/span/div/div</value>
      <webElementGuid>d284cf0c-ecc4-4dd8-8b15-fdf2e754985a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Steam'])[3]/following::div[2]</value>
      <webElementGuid>deb9281e-8da5-48bf-9b46-80ffd69146c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ahq'])[1]/following::div[4]</value>
      <webElementGuid>6959ac47-af47-44d0-a01a-98307915b785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YouTube'])[1]/preceding::div[1]</value>
      <webElementGuid>838fbe14-53eb-40f3-8273-fb049a69eb02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Discord']/parent::*</value>
      <webElementGuid>0b51e8ef-bec4-4ce0-824a-3700905a3829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[7]/span/span/div/div</value>
      <webElementGuid>ec855799-448d-4bd4-9891-b952fc326770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Discord' or . = 'Discord')]</value>
      <webElementGuid>eaaa6d20-d9a7-45d4-beb5-787ba489611f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
