<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User_email</name>
   <tag></tag>
   <elementGuidId>ab841523-40d3-45b7-92b8-366a16f81326</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='i6f2ae881-03bd-11ef-a2b2-d5fa05159792']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i6f2ae881-03bd-11ef-a2b2-d5fa05159792</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email input&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>368c1f82-ac96-4350-89bf-6cf43368394d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b6a96f4-46e5-4b2b-bac6-20ea2225c098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i6f2ae881-03bd-11ef-a2b2-d5fa05159792</value>
      <webElementGuid>6e9a2706-9c2d-473f-a814-a7981e7407b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>85c75196-8f3d-4ee6-b0bc-d8731b21b658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFieldText</value>
      <webElementGuid>013eac9c-6cbc-452d-92b1-69d795b03c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email input</value>
      <webElementGuid>427f097d-fff3-4623-9f85-47ba84695c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i6f2ae881-03bd-11ef-a2b2-d5fa05159792&quot;)</value>
      <webElementGuid>db9f1c45-83cf-408a-835c-2e13de2ebfc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='i6f2ae881-03bd-11ef-a2b2-d5fa05159792']</value>
      <webElementGuid>8a774348-f64a-4284-87f7-bff122926d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i6f2ae881-03bd-11ef-a2b2-d5fa05159792-row']/div[2]/div/div/input</value>
      <webElementGuid>733cd1e1-ecdd-4eef-8223-4baf93386a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>703f8d92-24ef-422a-b567-5b6fb27f45fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'i6f2ae881-03bd-11ef-a2b2-d5fa05159792' and @name = 'email']</value>
      <webElementGuid>a9f5343c-109c-4b51-b85c-79b06b0263fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
