<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User_email_1</name>
   <tag></tag>
   <elementGuidId>14ed5c7e-66ab-4511-b67b-8a197e993ce9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='i81f2f3e1-03bd-11ef-ae81-c31adc5d777e']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i81f2f3e1-03bd-11ef-ae81-c31adc5d777e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email input&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5128c096-955d-4745-b68b-d9cc2679abce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>392558b1-d86a-4595-837b-10e651b8fcfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i81f2f3e1-03bd-11ef-ae81-c31adc5d777e</value>
      <webElementGuid>f4f4e233-12f5-4a6b-a302-32a3fb7a5d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>4cf425d5-0407-4397-9f66-242c9d0ae194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFieldText</value>
      <webElementGuid>d2107ca5-c24b-4baa-b2a9-15430560c3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email input</value>
      <webElementGuid>e43fbb17-d304-47f1-91cd-bee71ead593d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i81f2f3e1-03bd-11ef-ae81-c31adc5d777e&quot;)</value>
      <webElementGuid>4e138cd4-c6d3-4528-9d99-37fa6b996f24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='i81f2f3e1-03bd-11ef-ae81-c31adc5d777e']</value>
      <webElementGuid>fb642bcf-29e0-4d9e-bcfa-2a0508aa278f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i81f2f3e1-03bd-11ef-ae81-c31adc5d777e-row']/div[2]/div/div/input</value>
      <webElementGuid>9fb82456-57b8-4eea-9123-839c253b6945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>53de93c3-5980-4a01-b055-b14c1592e7d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'i81f2f3e1-03bd-11ef-ae81-c31adc5d777e' and @name = 'email']</value>
      <webElementGuid>07871346-937b-4a6e-8401-79baabd07835</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
