<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_password</name>
   <tag></tag>
   <elementGuidId>ac5c1483-e9c2-4072-afd6-046ae350575f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='i81f34201-03bd-11ef-ae81-c31adc5d777e']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i81f34201-03bd-11ef-ae81-c31adc5d777e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Password input&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ecb9aefd-8735-4335-b754-66359d0f0da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3833d828-32a8-45ba-a25d-bfcf7f74d8ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i81f34201-03bd-11ef-ae81-c31adc5d777e</value>
      <webElementGuid>a7e9b972-bd8d-4715-93fb-94ad01e4520c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>134df016-d8f3-4543-8ce1-4e6c25b4ecee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFieldPassword</value>
      <webElementGuid>f39310a8-9f4d-4acc-896c-0a7780329ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Password input</value>
      <webElementGuid>a159122c-9a75-4522-8414-93ab3cc0a672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i81f34201-03bd-11ef-ae81-c31adc5d777e&quot;)</value>
      <webElementGuid>fb02d7a7-bf09-4e8a-a30d-265bce36efe9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='i81f34201-03bd-11ef-ae81-c31adc5d777e']</value>
      <webElementGuid>367badb0-c24a-41d9-8f8a-ece8a1d7845a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i81f34201-03bd-11ef-ae81-c31adc5d777e-row']/div[2]/div/div/input</value>
      <webElementGuid>45cc7952-f27a-42a6-a6bf-f54eaf2b9a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>0ece995f-50b4-4cb2-a9a1-566f88f7813b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'i81f34201-03bd-11ef-ae81-c31adc5d777e' and @name = 'password']</value>
      <webElementGuid>1cf2a75b-e6d5-4930-9383-76169a421426</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
