<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_ie bd-pfc-24-general-discussion-en_SubAhqString</name>
   <tag></tag>
   <elementGuidId>d7268495-2075-43bd-b5b5-271e908adb5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ib42d4831-039d-11ef-96a9-0f4d9f710d88']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ib42d4831-039d-11ef-96a9-0f4d9f710d88</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;SubAhqString&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bc470bf9-676c-419f-99f6-5e7e9ab2bc7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiTextArea euiTextArea--resizeVertical</value>
      <webElementGuid>b45c5630-0940-47dc-9ee1-0e0411e207ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>SubAhqString</value>
      <webElementGuid>f06a26e4-d5d4-4536-93e5-40564eca634a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>1a32f664-d356-400d-bad0-9154eea321ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>c6e313ec-1730-44ed-804b-6f2b18bd17b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubAhqString</value>
      <webElementGuid>3241d3d5-3039-4086-a5b2-2982ac4b86f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ib42d4831-039d-11ef-96a9-0f4d9f710d88</value>
      <webElementGuid>b7ac7cb3-47e6-4e0d-bf6a-6be9ad4e8ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ib42d4831-039d-11ef-96a9-0f4d9f710d88&quot;)</value>
      <webElementGuid>9b716964-934f-41dc-8ba4-38ac21edade0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ib42d4831-039d-11ef-96a9-0f4d9f710d88']</value>
      <webElementGuid>e88bef2b-0424-45c2-a8b9-070887999446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ib42d4831-039d-11ef-96a9-0f4d9f710d88-row']/div/textarea</value>
      <webElementGuid>1dbe52d1-7395-4dff-885f-ca42e6578e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/textarea</value>
      <webElementGuid>e91dd363-a2d9-4e12-8268-cbd5d0ad15ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'SubAhqString' and @id = 'ib42d4831-039d-11ef-96a9-0f4d9f710d88']</value>
      <webElementGuid>733942b5-b0c1-4289-9454-a6ea2e986497</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
