<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_concat(Select , , Copy channel ID,_bbc41f</name>
   <tag></tag>
   <elementGuidId>5f3b17b3-aaa2-439b-bd14-a59623aca9ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='i54053c01-039e-11ef-a593-af9600cebe4c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i54053c01-039e-11ef-a593-af9600cebe4c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;AppsIdsString&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a0196df2-cdb6-4898-a4de-faf39a952274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiTextArea euiTextArea--resizeVertical</value>
      <webElementGuid>1c4b1e68-3801-4081-bb43-b68e7b171a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>AppsIdsString</value>
      <webElementGuid>0c13d9db-d955-43ed-ade8-6816915bce32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>7c97ecf8-ff1c-482a-bc80-6df1aa7502c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>63f15bb6-6884-44b4-aafd-285438e8996f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AppsIdsString</value>
      <webElementGuid>e23cb18a-7607-46b1-9ed6-607743dbbe9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i54053c01-039e-11ef-a593-af9600cebe4c</value>
      <webElementGuid>40ccd6c3-910a-401a-bf72-0697c3e9b829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i54053c01-039e-11ef-a593-af9600cebe4c&quot;)</value>
      <webElementGuid>90f227db-14dd-43c0-8d1d-2644770ed476</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='i54053c01-039e-11ef-a593-af9600cebe4c']</value>
      <webElementGuid>f4427254-cf97-4ff5-b2c4-54b6be1483d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i54053c01-039e-11ef-a593-af9600cebe4c-row']/div/textarea</value>
      <webElementGuid>946d3603-6682-4e85-95df-288aac8de095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/textarea</value>
      <webElementGuid>a2cf4a8d-6f35-499a-8b4d-531fd04aad1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'AppsIdsString' and @id = 'i54053c01-039e-11ef-a593-af9600cebe4c']</value>
      <webElementGuid>71c9df49-5a2e-4bb5-b223-a8b3f777712a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
