<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_eghttpsstore.steampowered.comapp S_dc04ea</name>
   <tag></tag>
   <elementGuidId>5b9c1db7-165a-4e96-8f86-9e79a4027330</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='i4d7c1bb1-039e-11ef-a593-af9600cebe4c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i4d7c1bb1-039e-11ef-a593-af9600cebe4c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;AppsIdsString&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a0b018f6-928a-4c36-a2d8-99a1f3b9045d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiTextArea euiTextArea--resizeVertical</value>
      <webElementGuid>40b6b63b-affc-4a9c-8783-932f1fdc8df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>AppsIdsString</value>
      <webElementGuid>4016c2af-11f6-414c-ace0-04791f8dafc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>c0fe0fd7-402e-47ad-941c-35b7854ca161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>b646f460-5252-450c-9473-ca6e944b22ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AppsIdsString</value>
      <webElementGuid>4c1b355b-7365-458b-9897-aaf96627a1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i4d7c1bb1-039e-11ef-a593-af9600cebe4c</value>
      <webElementGuid>4c0eccec-70e9-4d65-b4bd-5bde94e86fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i4d7c1bb1-039e-11ef-a593-af9600cebe4c&quot;)</value>
      <webElementGuid>174dac3b-9d9b-4693-aba7-7078d112a913</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='i4d7c1bb1-039e-11ef-a593-af9600cebe4c']</value>
      <webElementGuid>29c9385d-105a-4e1a-8c53-6962d5acd9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i4d7c1bb1-039e-11ef-a593-af9600cebe4c-row']/div/textarea</value>
      <webElementGuid>bc3cbf3b-64ba-46e6-8950-ebf325595158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/textarea</value>
      <webElementGuid>64b1e697-6a3e-47ce-9015-87b0a28b934e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'AppsIdsString' and @id = 'i4d7c1bb1-039e-11ef-a593-af9600cebe4c']</value>
      <webElementGuid>34218b9e-ec0f-4319-addf-ea132f9a18e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
