<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Finalizing the Configuration_AppsI_499cb1</name>
   <tag></tag>
   <elementGuidId>1e6b6e1c-9116-4ca2-9d58-0bab613c4c4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='i513ddea1-039e-11ef-a593-af9600cebe4c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i513ddea1-039e-11ef-a593-af9600cebe4c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;AppsIdsString&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bdae827d-ee36-4ee6-9061-7c93680cc541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiTextArea euiTextArea--resizeVertical</value>
      <webElementGuid>5326aa06-9a0c-44ad-ba70-f5cff1a3c073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>AppsIdsString</value>
      <webElementGuid>b0858357-384f-4915-a4d3-544c8a1c5941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>b39f5022-461b-43d9-b043-3a8117a9b704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>ea4890db-375c-4568-a65e-509d1a10cd1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AppsIdsString</value>
      <webElementGuid>ef836603-c9dc-44c1-ab17-8a90ffbba747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i513ddea1-039e-11ef-a593-af9600cebe4c</value>
      <webElementGuid>4ff421f6-7cdf-40e1-a481-325e8beeab02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i513ddea1-039e-11ef-a593-af9600cebe4c&quot;)</value>
      <webElementGuid>500ef1e8-33cc-4cef-8027-0bdb0b1b1a39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='i513ddea1-039e-11ef-a593-af9600cebe4c']</value>
      <webElementGuid>f479d22b-925c-4662-8610-800600765091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i513ddea1-039e-11ef-a593-af9600cebe4c-row']/div/textarea</value>
      <webElementGuid>15c0b19f-a24f-4c72-9070-fd88d7d6655c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/textarea</value>
      <webElementGuid>674923b2-216d-492d-8788-89ef313667c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'AppsIdsString' and @id = 'i513ddea1-039e-11ef-a593-af9600cebe4c']</value>
      <webElementGuid>a13f36d9-de8a-41d8-8eef-7814dcc2ca96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
