<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Box_BannerContent</name>
   <tag></tag>
   <elementGuidId>e9af8736-a1a9-4c82-a193-2c04aacfff38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='id20abba1-0251-11ef-b564-3faa52f9f025']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id20abba1-0251-11ef-b564-3faa52f9f025</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Banner content&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>60e1ffa4-6362-41e4-82cb-a4781985f594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiTextArea euiTextArea--resizeVertical</value>
      <webElementGuid>e70a0c4e-cf79-441d-ba1d-4edb52f71ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Banner content</value>
      <webElementGuid>99b339d7-aef1-408a-ab38-96c7198dc9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>140</value>
      <webElementGuid>4b30777f-3fbd-4336-be21-90cc93b521a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>bf795165-20cd-4fb6-be79-25067efc42da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BannerContent</value>
      <webElementGuid>abc1ca56-8d0b-40eb-aca0-56182788fffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id20abba1-0251-11ef-b564-3faa52f9f025</value>
      <webElementGuid>1e4d126e-be18-4ca2-8d79-0a5becb8eb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id20abba1-0251-11ef-b564-3faa52f9f025&quot;)</value>
      <webElementGuid>988c6563-d224-4941-97a5-83ccdd5339b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='id20abba1-0251-11ef-b564-3faa52f9f025']</value>
      <webElementGuid>c0505fed-fda2-4aa0-a8d2-b28c76492459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id20abba1-0251-11ef-b564-3faa52f9f025-row']/div/textarea</value>
      <webElementGuid>56de3237-37ea-4fc8-ae9c-e526ced7c601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div/div/textarea</value>
      <webElementGuid>f02128b9-9587-4989-bebe-868890c9af31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'BannerContent' and @id = 'id20abba1-0251-11ef-b564-3faa52f9f025']</value>
      <webElementGuid>6b8e4917-9f4c-4a6d-9eda-e4f05d851c8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
