<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Box_(Project, , s name.)</name>
   <tag></tag>
   <elementGuidId>1e673149-8316-45d2-9790-32bf173df756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id209f851-0251-11ef-b564-3faa52f9f025']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id209f851-0251-11ef-b564-3faa52f9f025</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Project name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffc7a0ed-7e6b-453a-a511-0e0a6af6e0eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ae6ef18-199a-46e1-810a-b8f027af6359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id209f851-0251-11ef-b564-3faa52f9f025</value>
      <webElementGuid>316cbbdc-e298-4f9b-9d83-25389632289e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>68dbf171-a519-4dcd-b0b3-64c84ed23e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFieldText</value>
      <webElementGuid>3551a05a-c360-4d8a-af22-4bce8452d8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Project name</value>
      <webElementGuid>3287a296-c9b8-43c1-8e34-f9fd8f2d2ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>0a8eca11-1aa9-47e5-ab72-4a35aef01368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id209f851-0251-11ef-b564-3faa52f9f025&quot;)</value>
      <webElementGuid>a16f9826-90db-4737-bc86-edfb0ff13452</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id209f851-0251-11ef-b564-3faa52f9f025']</value>
      <webElementGuid>2b91297e-ac6c-4fdc-a762-0a2cd7860883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id209f851-0251-11ef-b564-3faa52f9f025-row']/div/div/div/input</value>
      <webElementGuid>c9420580-aa7c-4e6a-b41c-8287b1c0a74e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>ab49402d-b8ae-439a-82f4-367e695768e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'id209f851-0251-11ef-b564-3faa52f9f025' and @name = 'Name']</value>
      <webElementGuid>b2a29f11-eaca-48ac-8d53-70f139382aa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
