<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Box_BannerLifetime</name>
   <tag></tag>
   <elementGuidId>e128af17-b367-4c5d-9200-c037c2287297</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id20abba3-0251-11ef-b564-3faa52f9f025']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id20abba3-0251-11ef-b564-3faa52f9f025</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Banner timeout&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee17b8b6-6efc-4c48-9ca9-38a1d8fc957b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>903154ab-6d81-4124-9533-f9af8eec3af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id20abba3-0251-11ef-b564-3faa52f9f025</value>
      <webElementGuid>53dfdc61-dc03-400f-864c-91a019a9433d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>02a4cbd9-525e-4937-9416-a31472ad534d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>967dd04b-afcc-40e2-aecd-768b609f65fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BannerLifetime</value>
      <webElementGuid>92d45bb3-80ae-43b3-91c0-9281224e92b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFieldNumber</value>
      <webElementGuid>a1c2514e-9850-4f22-8d72-861337f1ee48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Banner timeout</value>
      <webElementGuid>d5977f0a-f2f7-42e5-8543-f0a1439ef533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>id20abba3-0251-11ef-b564-3faa52f9f025-help</value>
      <webElementGuid>1f0f7915-351f-4437-9a00-9717937e950e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id20abba3-0251-11ef-b564-3faa52f9f025&quot;)</value>
      <webElementGuid>2374b67d-be8f-483a-9edd-bfaec52fdad1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id20abba3-0251-11ef-b564-3faa52f9f025']</value>
      <webElementGuid>86a0064b-a2ce-4aca-808b-b200c8ce77bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id20abba3-0251-11ef-b564-3faa52f9f025-row']/div/div/div/input</value>
      <webElementGuid>890b2678-e477-40e4-82fd-5561401ee9b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>037a6af3-6098-49b5-82ac-d8ac9db15fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'id20abba3-0251-11ef-b564-3faa52f9f025' and @name = 'BannerLifetime']</value>
      <webElementGuid>32541c4d-9011-4eb2-a021-db4f66c993fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
