<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Box_(Project, , s description.)</name>
   <tag></tag>
   <elementGuidId>db6783a4-026c-4253-a96d-5cff887b326c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='id209f853-0251-11ef-b564-3faa52f9f025']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id209f853-0251-11ef-b564-3faa52f9f025</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Project description&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b2f4071e-cbc1-405a-b2db-3ac97b52192d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiTextArea euiTextArea--resizeVertical</value>
      <webElementGuid>603f56ad-85c0-4fcb-b5b3-a86ac9bd85c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Project description</value>
      <webElementGuid>78cc00a2-03e6-4ec6-a8a9-07362d5b89fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>140</value>
      <webElementGuid>fb5fdf51-23be-4c1c-b8f9-9f1ce6806df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>2453cd68-542e-4e99-b110-5ca0c641f843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>76e4ce6e-f8e0-426c-a53e-82253a44abe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id209f853-0251-11ef-b564-3faa52f9f025</value>
      <webElementGuid>3db807b6-bfb3-4af5-920c-124e5f659052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id209f853-0251-11ef-b564-3faa52f9f025&quot;)</value>
      <webElementGuid>0a10abf0-71f8-4440-917d-e7c61fdd93df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='id209f853-0251-11ef-b564-3faa52f9f025']</value>
      <webElementGuid>5245ebc4-c60c-4c83-903e-96d87fbac5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id209f853-0251-11ef-b564-3faa52f9f025-row']/div/textarea</value>
      <webElementGuid>5139c291-c84a-49c2-b3c6-a20664c4eb69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>35152b6e-30bf-41c3-983a-15ef0844495b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'Description' and @id = 'id209f853-0251-11ef-b564-3faa52f9f025']</value>
      <webElementGuid>da413724-eb42-476f-87e9-fdb47cae766a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
