<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Upload_Avatar</name>
   <tag></tag>
   <elementGuidId>798e3eca-8822-4d52-987e-7279b538d879</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Avatar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Avatar&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Avatar upload file&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>636c349c-bb1c-41af-9781-d2c9ac490b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>65efd9ad-a80b-45ee-a13e-e04f2e8563ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Avatar</value>
      <webElementGuid>1e2dddf6-a8c0-49af-8a0d-a4481ccfb2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFilePicker__input</value>
      <webElementGuid>ed888d5d-0b14-4040-8b99-faa09cf9224c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>i622098a1-0274-11ef-a63d-ab9ce65c6ed3</value>
      <webElementGuid>1e7af55a-5ca6-4130-b6f1-dbfde1410013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Avatar upload file</value>
      <webElementGuid>6a16f198-433a-4c00-a077-31f112061c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i621ec3e1-0274-11ef-a63d-ab9ce65c6ed3-row&quot;)/div[@class=&quot;euiFormRow__fieldWrapper&quot;]/div[@class=&quot;euiFilePicker&quot;]/div[@class=&quot;euiFilePicker__wrap&quot;]/input[@class=&quot;euiFilePicker__input&quot;]</value>
      <webElementGuid>1b494577-64a4-46a8-a940-f49168f96192</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Avatar']</value>
      <webElementGuid>c41ddbc1-b68e-4188-9a0e-b12d3378959a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i621ec3e1-0274-11ef-a63d-ab9ce65c6ed3-row']/div[2]/div/div/input</value>
      <webElementGuid>a2602e11-c28f-48cc-bf96-42f74371bf16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ee171bd7-f999-4158-ba0f-838cc2594546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'Avatar']</value>
      <webElementGuid>90e9c684-61cb-4e84-a9e9-0a55e68084c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
