<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Box_Password</name>
   <tag></tag>
   <elementGuidId>46b99872-301f-4513-be9a-30fa382e9b31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='i11c497b1-023a-11ef-9b48-353c97479f22']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i11c497b1-023a-11ef-9b48-353c97479f22</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Password input&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>103e1984-8c87-4dda-90b7-5e10bda2d833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>059631fa-2b70-4b73-97e2-d3a97bcd4730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i11c497b1-023a-11ef-9b48-353c97479f22</value>
      <webElementGuid>372b6a62-43f0-4779-a8e4-96849451193e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>75278e96-c53d-4047-838d-02c713e2adf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFieldPassword</value>
      <webElementGuid>62f02a14-6832-4677-8bef-eb048508dec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Password input</value>
      <webElementGuid>f4b35976-bc51-477c-bf0e-905565dd07ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i11c497b1-023a-11ef-9b48-353c97479f22&quot;)</value>
      <webElementGuid>05efdd98-4c01-410a-a9e7-c6ed0f166d5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='i11c497b1-023a-11ef-9b48-353c97479f22']</value>
      <webElementGuid>aea542b4-2e62-4d61-9692-6cc111baf9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i11c497b1-023a-11ef-9b48-353c97479f22-row']/div[2]/div/div/input</value>
      <webElementGuid>fde4889c-f217-4e12-b729-ab94fa6abfbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>fa54562a-ae5f-4a33-91ec-b0f65410722c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'i11c497b1-023a-11ef-9b48-353c97479f22' and @name = 'password']</value>
      <webElementGuid>a2ee6d77-92da-4361-a9de-645d62090ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='i8f3a3b41-021d-11ef-820f-ffa9cc3b0cce']</value>
      <webElementGuid>13d1e1ea-e8a3-4269-8f0b-f4f40c4b47e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i8f3a3b41-021d-11ef-820f-ffa9cc3b0cce-row']/div[2]/div/div/input</value>
      <webElementGuid>78e7229e-44cf-4301-94b5-ab77da7e33a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'i8f3a3b41-021d-11ef-820f-ffa9cc3b0cce' and @name = 'password']</value>
      <webElementGuid>261b2fd8-3edc-4d99-9644-7f88a630bce0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
