<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Box_User_email</name>
   <tag></tag>
   <elementGuidId>a497faf3-85d4-44c4-ac99-38853bcae6d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='i11c44991-023a-11ef-9b48-353c97479f22']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i11c44991-023a-11ef-9b48-353c97479f22</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'i8f3a1431-021d-11ef-820f-ffa9cc3b0cce' and @name = 'email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email input&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>115e1cc4-1ac9-4924-8972-290845a194f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e688a2d4-447a-4c40-91cb-0034c6cac671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i11c44991-023a-11ef-9b48-353c97479f22</value>
      <webElementGuid>e41644b6-dfff-4909-b65b-fcc521512cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>b9e8f01e-ec95-4dec-b5fa-1893777f1281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>euiFieldText</value>
      <webElementGuid>7d524397-511a-49f4-bda7-32e159546d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email input</value>
      <webElementGuid>78a645f2-b37d-43e7-8c66-a3aaff91dc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i11c44991-023a-11ef-9b48-353c97479f22&quot;)</value>
      <webElementGuid>a8c332f4-0605-4b13-bc3e-168da25469fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='i11c44991-023a-11ef-9b48-353c97479f22']</value>
      <webElementGuid>c64fcca5-036d-450e-9bd6-2c83cfe8db1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i11c44991-023a-11ef-9b48-353c97479f22-row']/div[2]/div/div/input</value>
      <webElementGuid>7b0410d8-0a2c-4f60-85c1-58ce534f9b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9989dac6-ce95-4f51-8df1-a01b7431cc81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'i11c44991-023a-11ef-9b48-353c97479f22' and @name = 'email']</value>
      <webElementGuid>4ec5c5ee-39b5-4f7e-9e08-4cd7d8739c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='i8f3a1431-021d-11ef-820f-ffa9cc3b0cce']</value>
      <webElementGuid>a634c12c-180b-42ca-8548-b6af7fa53761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i8f3a1431-021d-11ef-820f-ffa9cc3b0cce-row']/div[2]/div/div/input</value>
      <webElementGuid>2fb2070e-26e6-40f5-88de-973dce51f8ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'i8f3a1431-021d-11ef-820f-ffa9cc3b0cce' and @name = 'email']</value>
      <webElementGuid>3cebbdfd-2512-4326-ae78-6d2c2aa1f34e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
